image: golang:1.10
pipelines:
  default:
    - step:
        script:
          - go version
          - apk update && apk add git
          - mkdir -p "$GOPATH/src/mellium.im/"
          - ln -s "`pwd`" "$GOPATH/src/mellium.im/httprouter"
          - cd "$GOPATH/src/mellium.im/httprouter"
          - go vet ./...
          - go test -race ./...
          - go test -cover ./...
